# Generated by Django 6.1.1 on 2026-09-21 19:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asiento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20)),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('BLOQUEADO', 'Bloqueado'), ('VENDIDO', 'Vendido')], default='DISPONIBLE', max_length=20)),
            ],
            options={
                'db_table': 'asientos',
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=160)),
                ('fecha', models.DateTimeField()),
                ('lugar', models.CharField(max_length=160)),
                ('estado', models.CharField(choices=[('PUBLICADO', 'Publicado'), ('CERRADO', 'Cerrado'), ('CANCELADO', 'Cancelado')], default='PUBLICADO', max_length=20)),
            ],
            options={
                'db_table': 'eventos',
            },
        ),
        migrations.CreateModel(
            name='SolicitudCompra',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('CONFIRMADA', 'Confirmada'), ('RECHAZADA', 'Rechazada')], default='CONFIRMADA', max_length=20)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'db_table': 'solicitudes_compra',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=160, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('rol', models.CharField(choices=[('USUARIO', 'Usuario'), ('ADMIN', 'Administrador')], default='USUARIO', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='Bloqueo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_expiracion', models.DateTimeField()),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('LIBERADO', 'Liberado'), ('CONFIRMADO', 'Confirmado')], default='ACTIVO', max_length=20)),
                ('asiento', models.OneToOneField(db_column='asiento_id', on_delete=django.db.models.deletion.CASCADE, related_name='bloqueo', to='core.asiento')),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, related_name='bloqueos', to='core.usuario')),
            ],
            options={
                'db_table': 'bloqueos',
            },
        ),
        migrations.AddField(
            model_name='asiento',
            name='evento',
            field=models.ForeignKey(db_column='evento_id', on_delete=django.db.models.deletion.CASCADE, related_name='asientos', to='core.evento'),
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('asiento', models.OneToOneField(db_column='asiento_id', on_delete=django.db.models.deletion.CASCADE, related_name='detalle_compra', to='core.asiento')),
                ('solicitud', models.ForeignKey(db_column='solicitud_id', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='core.solicitudcompra')),
            ],
            options={
                'db_table': 'detalle_compra',
            },
        ),
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('accion', models.CharField(max_length=80)),
                ('recurso', models.CharField(max_length=120)),
                ('resultado', models.CharField(max_length=30)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('bloqueo', models.ForeignKey(blank=True, db_column='bloqueo_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias', to='core.bloqueo')),
                ('solicitud', models.ForeignKey(blank=True, db_column='solicitud_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias', to='core.solicitudcompra')),
            ],
            options={
                'db_table': 'auditoria',
            },
        ),
        migrations.AddField(
            model_name='solicitudcompra',
            name='usuario',
            field=models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='core.usuario'),
        ),
        migrations.AlterUniqueTogether(
            name='asiento',
            unique_together={('evento', 'codigo')},
        ),
    ]
